## Lesson 1: Toy Differential Privacy - Simple Database Queries

## Differential privacy 
It ensures that the removal or addition of a single database item does not significantly affect the outcome of any analysis, thereby protecting individual privacy. This means that an observer cannot determine whether a particular individual's information is included in the dataset, even if they have access to the output of the analysis.


# Create a simple 
#Step one is to create our database - we're going to do this by initializing a random list of 1s and 0s (which are the entries in our database). Note - the number of entries directly corresponds to #the number of people in our database.


In [1]:
import torch

num_entries = 5000
db= torch.rand(num_entries)> 0.5
db

tensor([False,  True, False,  ..., False, False,  True])

## Project: Generate Parallel Databases

Key to the definition of differenital privacy is the ability to ask the question "When querying a database, if I removed someone from the database, would the output of the query be any different?". Thus, in order to check this, we must construct what we term "parallel databases" which are simply databases with one entry removed.

In this first project, I want you to create a list of every parallel database to the one currently contained in the "db" variable. Then, I want you to create a function which both:

creates the initial database (db)

creates all parallel databases

In [2]:
db.shape

torch.Size([5000])

In [3]:
db[0:2]

tensor([False,  True])

In [4]:
remove_index=2


In [5]:
db[3:]

tensor([ True, False, False,  ..., False, False,  True])

In [7]:
#concatenate both tensor
torch.cat((db[0:2],db[3:]))[0:5]

tensor([False,  True,  True, False, False])

In [9]:
# define function
def get_parallel_db(db,remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [12]:
get_parallel_db(db,2)[0:5]

tensor([False,  True,  True, False, False])

In [8]:
# Singe datapoint removed
get_parallel_db(db,2).shape

torch.Size([4999])

In [19]:
#Parallel_db

def get_parallel_dbs(db):
    parallel_dbs=list()

    for i in range(len(db)):
        pdb=get_parallel_db(db,i)
        parallel_dbs.append(pdb)

In [21]:
pbds=get_parallel_dbs(db)
pbds

In [23]:
print(pbds)

None


In [28]:
def create_db_and_parallels(num_entries):
    db=torch.rand(num_entries)>0.5
    pbds=get_parallel_dbs(db)

    return db,pbds
    

In [35]:
db,pbds=create_db_and_parallels(20)

In [36]:
db[0:8]

tensor([False,  True, False,  True, False,  True,  True,  True])

In [38]:
pbds